# .github/workflows/ci.yml

name: CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Create virtual environment
      run: |
        python -m venv .venv
    - name: Install `uv` in virtual environment
      run: |
        .venv/bin/pip install uv
    - name: Install dependencies using `uv`
      run: |
        .venv/bin/uv pip install -r requirements.txt
    - name: Run tests
      run: |
        .venv/bin/pytest test/
